config/routes.rb
Funkyouseven::Application.routes.draw do
  devise_for :users

  post 'markdown/preview'

  match '/size_to_product_count/:product_id/:size_id/:product_count', :to => 'size_to_products#size_to_product_count', :as => :size_to_product_count

  match '/cover_magazines/new_from_post/:post_id', :to => "cover_magazines#new_from_post", :as => :create_cover_magazine_from_post
  resources :cover_magazines

  resources :posts

  match '/products/all/page/:page', :to => "products#all_by_page", :as => :all_products_by_page
  match '/products/section/:section/sex/:sex', :to => "products#sex", :as => :products_by_sex
  match '/products/section/:section/career/:career', :to => "products#career", :as => :products_by_career
  match '/products/section/:section/page/:page', :to => "products#page", :as => :products_by_page
  match '/products/funk_yoo_shot' => "products#funk_yoo_shot", :via => :get
  resources :products

  match '/product_to_look/:product_id/:look_id/:yes', :to => 'product_to_looks#check'

  match '/basket/remove/:product_id/:size_id', :to => 'basket#remove_product', :as => :remove_from_basket
  match '/basket/add/:product_id/:size_id', :to => 'basket#add_product', :as => :add_to_basket
  match '/basket/update_size/:product_count/:product_id/:size_id', :to => 'basket#update_size', :as => :update_size
  match '/basket/empty', :to => 'basket#empty', :as => 'empty_basket', :as => :empty_basket
  match '/basket/:product_count/:product_id/:size_id', :to => 'basket#set_count', :as => :set_count
  match '/basket' => 'basket#my_basket', :as => :my_basket

  resources :orders

  resources :shop_sections
  resources :section_categories
  resources :brands

  match '/shop/not_publish' => 'products#not_publish', :as => :shop_not_publish
  match '/shop/archive' => 'products#archive', :as => :shop_archive
  match '/shop/import_catalog' => 'products#import_catalog', :as => :shop_import_catalog
  match '/shop/brands' => 'brands#index', :as => :shop_brands
  match '/shop/:shop_section' => 'products#index', :as => :shop_section_products
  match '/shop/:shop_section/:section_category' => 'products#index', :as => :section_category_products

  match '/product_images/crop/:id' => 'product_images#crop', :as => :crop_product_image
  match '/product_images/update/:id/:cover/:preview/:title' => 'product_images#update'
  match '/product_images/destroy/:id' => 'product_images#destroy'
  match '/product_images/upload' => 'product_images#upload'
  resources :product_images

  match '/post_images/crop/:id' => 'post_images#crop', :as => :crop_post_image
  match '/post_images/update/:id/:cover/:preview/:title' => 'post_images#update'
  match '/post_images/destroy/:id' => 'post_images#destroy'
  match '/post_images/upload' => 'post_images#upload'
  resources :post_images

  match '/magazine' => 'posts#index', :as => :magazine
  match '/magazine/:short_url' => 'posts#show', :as => :magazine_post

  match '/:short_url' => 'statics#show', :as => :show_static
  resources :statics

  resources :welcomes

  root :to => 'welcomes#home'

  match '/access_denied' => 'error#access_denied', :as => :access_denied
  match '/not_found' => 'error#not_found', :as => :not_found
end

app/models/cover_magazine.rb
class CoverMagazine < ActiveRecord::Base
  attr_accessible :columns, :columns_html_data, :cover_css, :cover_html, :cover_js, :release_date, :sequence_number, :special, :special_html_data, :subject, :subject_html_data, :title, :title_html_data, :year_number, :title_font_data

  has_many :articles, :class_name => 'Post', :foreign_key => :cover_id

  scope :last_number, where("cover_magazines.release_date < ?", DateTime.now).order("id DESC").limit(1)
  scope :last_number_admin, order("id DESC").limit(1)
  default_scope order("id DESC")

  def initialize(*args)
    super
    if self.new_record?

      self.title = I18n.t("activerecord.attributes.cover_magazine.title")
      self.subject = I18n.t("activerecord.attributes.cover_magazine.subject")
      self.special = I18n.t("activerecord.attributes.cover_magazine.special")
      self.columns = I18n.t("activerecord.attributes.cover_magazine.columns")

      self.sequence_number = 1 + CoverMagazine.last_number.first().sequence_number unless CoverMagazine.last_number.empty?
      self.year_number = 1 + CoverMagazine.last_number.first().year_number unless CoverMagazine.last_number.empty?
    end
  end

  def self.new_from_post(post_id)
    post = self.new

    main_article = Post.find(post_id)
    post.title = main_article.title
    post.subject = main_article.description
    return post
  end

  def get_cover
    self.main_article.get_cover() unless self.main_article.nil?
  end

  def main_article
    Post.find_by_cover_id_and_main_article(self.id, true)
  end

end

app/controllers/cover_magazines_controller.rb
class CoverMagazinesController < ApplicationController
  # GET /cover_magazines
  # GET /cover_magazines.json
  def index
    @cover_magazines = CoverMagazine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cover_magazines }
    end
  end

  # GET /cover_magazines/1
  # GET /cover_magazines/1.json
  def show
    @cover_magazine = CoverMagazine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cover_magazine }
    end
  end

  # GET /cover_magazines/new
  # GET /cover_magazines/new.json
  def new
    @cover_magazine = CoverMagazine.new

    respond_to do |format|
      format.html { render layout: "editor" }
      format.json { render json: @cover_magazine }
    end
  end

  # GET /cover_magazines/new
  # GET /cover_magazines/new.json
  def new_from_post()
    unless params[:post_id].nil?
      @cover_magazine = CoverMagazine.new_from_post(params[:post_id])
    else
      @cover_magazine = CoverMagazine.new
    end

    render :layout => false

  end

  # GET /cover_magazines/1/edit
  def edit
    @cover_magazine = CoverMagazine.find(params[:id])
    render layout: "editor"
  end

  # POST /cover_magazines
  # POST /cover_magazines.json
  def create
    @cover_magazine = CoverMagazine.new(params[:cover_magazine])

    respond_to do |format|
      if @cover_magazine.save
        format.html { redirect_to magazine_path, notice: 'Cover magazine was successfully created.' }
        format.json { render json: @cover_magazine, status: :created, location: @cover_magazine }
      else
        format.html { render action: "new" }
        format.json { render json: @cover_magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cover_magazines/1
  # PUT /cover_magazines/1.json
  def update
    @cover_magazine = CoverMagazine.find(params[:id])

    respond_to do |format|
      if @cover_magazine.update_attributes(params[:cover_magazine])
        format.html { redirect_to magazine_path, notice: 'Cover magazine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cover_magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cover_magazines/1
  # DELETE /cover_magazines/1.json
  def destroy
    @cover_magazine = CoverMagazine.find(params[:id])
    @cover_magazine.destroy

    respond_to do |format|
      format.html { redirect_to cover_magazines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cover_magazines_helper.rb
module CoverMagazinesHelper
end

app/views/cover_magazines/_form.html.erb
<%= form_for(@cover_magazine) do |f| %>
    <% if @cover_magazine.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@cover_magazine.errors.count, "error") %> prohibited this cover_magazine from being
            saved:</h2>
          <ul>
            <% @cover_magazine.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="magazine_cover">
      <%= image_tag @cover_magazine.get_cover().image.url(:album_normal), :alt => @cover_magazine.title, :class => "magazine_cover_background" unless @cover_magazine.main_article.nil? %>

      <div class="magazine_cover_title draggable" style="<%= raw @cover_magazine.title_html_data %>" font_data="<%= raw @cover_magazine.title_font_data %>">
        <%= raw format_title(@cover_magazine.title) %>
      </div>
      <div class="magazine_cover_subject draggable" style="<%= raw @cover_magazine.subject_html_data %>">
        <%= raw @cover_magazine.subject %>
      </div>
      <div class="magazine_cover_special draggable" style="<%= raw @cover_magazine.special_html_data %>">
        <%= raw format_html_data(@cover_magazine.special) %>
      </div>
      <div class="magazine_cover_columns  draggable" style="<%= raw @cover_magazine.columns_html_data %>">
        <%= raw format_html_data(@cover_magazine.columns) %>
      </div>
    </div>
    <div class="clear-8"></div>


    <div class="vertical_block">
      <div class="field third">
        <%= f.label :release_date %>
        <br/>
        <%= f.date_select :release_date %>
      </div>
      <div class="field third">
        <%= f.label :year_number %>
        <br/>
        <%= f.number_field :year_number %>
      </div>
      <div class="field third">
        <%= f.label :sequence_number %>
        <br/>
        <%= f.number_field :sequence_number %>
      </div>
    </div>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :subject %>
      <br/>
      <%= f.text_area :subject %>
    </div>

    <div class="vertical_block">
      <div class="field half">
        <%= f.label :columns %>
        <br/>
        <%= f.text_area :columns %>
      </div>
      <div class="field half">
        <%= f.label :special %>
        <br/>
        <%= f.text_area :special %>
      </div>
    </div>

    <!--<div class="field">-->
    <%#= f.label :cover_html %>
    <!--<%#= f.text_area :cover_html %>-->
    <!--</div>-->
    <!--<div class="field">-->
    <%#= f.label :cover_css %>
    <!--<%#= f.text_area :cover_css %>-->
    <!--</div>-->
    <!--<div class="field">-->
    <%#= f.label :cover_js %>
    <!--<%#= f.text_area :cover_js %>-->
    <!--</div>-->

    <div class="clear-8"></div>

    <%= f.hidden_field :title_html_data %>
    <%= f.hidden_field :title_font_data %>
    <%= f.hidden_field :subject_html_data %>
    <%= f.hidden_field :columns_html_data %>
    <%= f.hidden_field :special_html_data %>

    <div class="instrumental-dock draggable">
      <%= label_tag :font_color, t("activerecord.attributes.cover_magazine.font_color") %>
      <br/>
      <%= text_field_tag :font_color, "000000" %>
      <br/>

      <%= label_tag :font_size, t("activerecord.attributes.cover_magazine.font_size") %>
      <br/>

      <div id="font_size" class="range_slider" min="0" max="144"></div>
      <br/>

      <%= label_tag :angle, t("activerecord.attributes.cover_magazine.angle") %>
      <br/>

      <div id="text_angle" class="range_slider" min="0" max="360"></div>
      <br/>

      <%= label_tag :font_data, raw(t("activerecord.attributes.cover_magazine.font_data") + link_to("(data:font)", "https://typekit.com/fonts?classification=decorative", :target => "_href")) %>
      <br/>
      <%= text_field_tag :font_data, @cover_magazine.title_font_data, :onkeyup => "update_slide_data('font_data');" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<style type="text/css">
    @font-face {
        font-family: coverMagazineTitle;
        font-style: normal;
        font-weight: 400;
        src: url("<%= @cover_magazine.title_font_data %>");
    }
</style>

app/views/cover_magazines/edit.html.erb
<div class="center_item">

  <div class="main noborder">
    <h1><%= t('backend.titles.editing', :model => t('activerecord.model.cover_magazine')) %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/cover_magazines/index.html.erb
<h1>Listing cover_magazines</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Title html data</th>
    <th>Release date</th>
    <th>Year number</th>
    <th>Sequence number</th>
    <th>Subject</th>
    <th>Subject html data</th>
    <th>Columns</th>
    <th>Columns html data</th>
    <th>Special</th>
    <th>Special html data</th>
    <th>Cover html</th>
    <th>Cover css</th>
    <th>Cover js</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cover_magazines.each do |cover_magazine| %>
  <tr>
    <td><%= cover_magazine.title %></td>
    <td><%= cover_magazine.title_html_data %></td>
    <td><%= cover_magazine.release_date %></td>
    <td><%= cover_magazine.year_number %></td>
    <td><%= cover_magazine.sequence_number %></td>
    <td><%= cover_magazine.subject %></td>
    <td><%= cover_magazine.subject_html_data %></td>
    <td><%= cover_magazine.columns %></td>
    <td><%= cover_magazine.columns_html_data %></td>
    <td><%= cover_magazine.special %></td>
    <td><%= cover_magazine.special_html_data %></td>
    <td><%= cover_magazine.cover_html %></td>
    <td><%= cover_magazine.cover_css %></td>
    <td><%= cover_magazine.cover_js %></td>
    <td><%= link_to 'Show', cover_magazine %></td>
    <td><%= link_to 'Edit', edit_cover_magazine_path(cover_magazine) %></td>
    <td><%= link_to 'Destroy', cover_magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cover magazine', new_cover_magazine_path %>

app/views/cover_magazines/new.html.erb
<div class="center_item">

  <div class="main noborder">
    <h1><%= t('backend.titles.creating', :model => t('activerecord.model.cover_magazine')) %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/cover_magazines/new_from_post.js.erb
$("#default-popup").html("<%= escape_javascript( render( :partial => "cover_magazines/form", :locals => { :target => @cover_magazine } ) ) %>");

openModal("#default-popup");

app/views/cover_magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @cover_magazine.title %>
</p>

<p>
  <b>Title html data:</b>
  <%= @cover_magazine.title_html_data %>
</p>

<p>
  <b>Release date:</b>
  <%= @cover_magazine.release_date %>
</p>

<p>
  <b>Year number:</b>
  <%= @cover_magazine.year_number %>
</p>

<p>
  <b>Sequence number:</b>
  <%= @cover_magazine.sequence_number %>
</p>

<p>
  <b>Subject:</b>
  <%= @cover_magazine.subject %>
</p>

<p>
  <b>Subject html data:</b>
  <%= @cover_magazine.subject_html_data %>
</p>

<p>
  <b>Columns:</b>
  <%= @cover_magazine.columns %>
</p>

<p>
  <b>Columns html data:</b>
  <%= @cover_magazine.columns_html_data %>
</p>

<p>
  <b>Special:</b>
  <%= @cover_magazine.special %>
</p>

<p>
  <b>Special html data:</b>
  <%= @cover_magazine.special_html_data %>
</p>

<p>
  <b>Cover html:</b>
  <%= @cover_magazine.cover_html %>
</p>

<p>
  <b>Cover css:</b>
  <%= @cover_magazine.cover_css %>
</p>

<p>
  <b>Cover js:</b>
  <%= @cover_magazine.cover_js %>
</p>


<%= link_to 'Edit', edit_cover_magazine_path(@cover_magazine) %> |
<%= link_to 'Back', cover_magazines_path %>