config/routes.rb
Funkyouseven::Application.routes.draw do
  devise_for :users

  post 'markdown/preview'

  match '/size_to_product_count/:product_id/:size_id/:product_count', :to => 'size_to_products#size_to_product_count', :as => :size_to_product_count

  match '/cover_magazines/new_from_post/:post_id', :to => "cover_magazines#new_from_post", :as => :create_cover_magazine_from_post
  resources :cover_magazines

  resources :posts

  match '/products/all/page/:page', :to => "products#all_by_page", :as => :all_products_by_page
  match '/products/section/:section/sex/:sex', :to => "products#sex", :as => :products_by_sex
  match '/products/section/:section/career/:career', :to => "products#career", :as => :products_by_career
  match '/products/section/:section/page/:page', :to => "products#page", :as => :products_by_page
  match '/products/funk_yoo_shot' => "products#funk_yoo_shot", :via => :get
  resources :products

  match '/product_to_look/:product_id/:look_id/:yes', :to => 'product_to_looks#check'

  match '/basket/remove/:product_id/:size_id', :to => 'basket#remove_product', :as => :remove_from_basket
  match '/basket/add/:product_id/:size_id', :to => 'basket#add_product', :as => :add_to_basket
  match '/basket/update_size/:product_count/:product_id/:size_id', :to => 'basket#update_size', :as => :update_size
  match '/basket/empty', :to => 'basket#empty', :as => 'empty_basket', :as => :empty_basket
  match '/basket/:product_count/:product_id/:size_id', :to => 'basket#set_count', :as => :set_count
  match '/basket' => 'basket#my_basket', :as => :my_basket

  resources :orders

  resources :shop_sections
  resources :section_categories
  resources :brands

  match '/shop/not_publish' => 'products#not_publish', :as => :shop_not_publish
  match '/shop/archive' => 'products#archive', :as => :shop_archive
  match '/shop/import_catalog' => 'products#import_catalog', :as => :shop_import_catalog
  match '/shop/brands' => 'brands#index', :as => :shop_brands
  match '/shop/:shop_section' => 'products#index', :as => :shop_section_products
  match '/shop/:shop_section/:section_category' => 'products#index', :as => :section_category_products

  match '/product_images/crop/:id' => 'product_images#crop', :as => :crop_product_image
  match '/product_images/update/:id/:cover/:preview/:title' => 'product_images#update'
  match '/product_images/destroy/:id' => 'product_images#destroy'
  match '/product_images/upload' => 'product_images#upload'
  resources :product_images

  match '/post_images/crop/:id' => 'post_images#crop', :as => :crop_post_image
  match '/post_images/update/:id/:cover/:preview/:title' => 'post_images#update'
  match '/post_images/destroy/:id' => 'post_images#destroy'
  match '/post_images/upload' => 'post_images#upload'
  resources :post_images

  match '/magazine' => 'posts#index', :as => :magazine
  match '/magazine/:short_url' => 'posts#show', :as => :magazine_post

  match '/:short_url' => 'statics#show', :as => :show_static
  resources :statics

  resources :welcomes

  root :to => 'welcomes#home'

  match '/access_denied' => 'error#access_denied', :as => :access_denied
  match '/not_found' => 'error#not_found', :as => :not_found
end

app/models/shop_section.rb
class ShopSection < ActiveRecord::Base
  attr_accessible :description, :name, :short_url, :list_order, :last_product_number

  scope :sections, where("short_url != ?", "brands")
  scope :main_menu, order(:list_order)

#  default_scope order(:name)

  has_many :products
  has_many :section_categories

  def empty_section_categories
    SectionCategory.unscoped.where("products_count = ? and shop_section_id = ?", 0, self.id).all
  end

end

app/controllers/shop_sections_controller.rb
class ShopSectionsController < ApplicationController
  load_and_authorize_resource

  # GET /shop_sections
  # GET /shop_sections.json
  def index
    @shop_sections = ShopSection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shop_sections }
    end
  end

  # GET /shop_sections/1
  # GET /shop_sections/1.json
  def show
    if params[:short_url]
      @shop_section = ShopSection.find_by_short_url(params[:short_url])
    else
      @shop_section = ShopSection.find(params[:id])
    end

    raise NotFound unless @shop_section

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop_section }
    end
  end

  # GET /shop_sections/new
  # GET /shop_sections/new.json
  def new
    @shop_section = ShopSection.new

    respond_to do |format|
      format.html { render layout: "editor" }
      format.json { render json: @shop_section }
    end
  end

  # GET /shop_sections/1/edit
  def edit
    @shop_section = ShopSection.find(params[:id])
    render layout: "editor"
  end

  # POST /shop_sections
  # POST /shop_sections.json
  def create
    @shop_section = ShopSection.new(params[:shop_section])

    respond_to do |format|
      if @shop_section.save
        format.html { redirect_to shop_section_products_path(@shop_section.short_url), notice: 'Shop section was successfully created.' }
        format.json { render json: @shop_section, status: :created, location: @shop_section }
      else
        format.html { render action: "new", layout: "editor" }
        format.json { render json: @shop_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shop_sections/1
  # PUT /shop_sections/1.json
  def update
    @shop_section = ShopSection.find(params[:id])

    respond_to do |format|
      if @shop_section.update_attributes(params[:shop_section])
        format.html { redirect_to shop_section_products_path(@shop_section.short_url), notice: 'Shop section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "editor" }
        format.json { render json: @shop_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_sections/1
  # DELETE /shop_sections/1.json
  def destroy
    @shop_section = ShopSection.find(params[:id])
    @shop_section.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/shop_sections_helper.rb
module ShopSectionsHelper
end

app/views/shop_sections/_form.html.erb
<%= form_for(@shop_section) do |f| %>
    <% if @shop_section.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shop_section.errors.count, "error") %> prohibited this shop_section from being saved:</h2>

          <ul>
            <% @shop_section.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :short_url %>
      <br/>
      <%= f.text_field :short_url %>
    </div>
    <div class="field">
      <%= f.label :list_order %>
      <br/>
      <%= f.number_field :list_order %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/shop_sections/edit.html.erb
<div class="center_item">

  <div class="main noborder">
    <h1><%= t('backend.titles.editing', :model => t('activerecord.model.shop_section')) %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/shop_sections/index.html.erb
<h1>Listing shop_sections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short url</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shop_sections.each do |shop_section| %>
  <tr>
    <td><%= shop_section.name %></td>
    <td><%= shop_section.short_url %></td>
    <td><%= shop_section.description %></td>
    <td><%= link_to 'Show', shop_section %></td>
    <td><%= link_to 'Edit', edit_shop_section_path(shop_section) %></td>
    <td><%= link_to 'Destroy', shop_section, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop section', new_shop_section_path %>

app/views/shop_sections/new.html.erb
<div class="center_item">

  <div class="main noborder">
    <h1><%= t('backend.titles.creating', :model => t('activerecord.model.shop_section')) %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/shop_sections/show.html.erb
<p>
  <b>Name:</b>
  <%= @shop_section.name %>
</p>

<p>
  <b>Short url:</b>
  <%= @shop_section.short_url %>
</p>

<p>
  <b>Description:</b>
  <%= @shop_section.description %>
</p>


<%= link_to 'Edit', edit_shop_section_path(@shop_section) %> |
<%= link_to 'Back', shop_sections_path %>