config/routes.rb
Funkyouseven::Application.routes.draw do
  devise_for :users

  post 'markdown/preview'

  match '/size_to_product_count/:product_id/:size_id/:product_count', :to => 'size_to_products#size_to_product_count', :as => :size_to_product_count

  match '/cover_magazines/new_from_post/:post_id', :to => "cover_magazines#new_from_post", :as => :create_cover_magazine_from_post
  resources :cover_magazines

  resources :posts

  match '/products/all/page/:page', :to => "products#all_by_page", :as => :all_products_by_page
  match '/products/section/:section/sex/:sex', :to => "products#sex", :as => :products_by_sex
  match '/products/section/:section/career/:career', :to => "products#career", :as => :products_by_career
  match '/products/section/:section/page/:page', :to => "products#page", :as => :products_by_page
  match '/products/funk_yoo_shot' => "products#funk_yoo_shot", :via => :get
  resources :products

  match '/product_to_look/:product_id/:look_id/:yes', :to => 'product_to_looks#check'

  match '/basket/remove/:product_id/:size_id', :to => 'basket#remove_product', :as => :remove_from_basket
  match '/basket/add/:product_id/:size_id', :to => 'basket#add_product', :as => :add_to_basket
  match '/basket/update_size/:product_count/:product_id/:size_id', :to => 'basket#update_size', :as => :update_size
  match '/basket/empty', :to => 'basket#empty', :as => 'empty_basket', :as => :empty_basket
  match '/basket/:product_count/:product_id/:size_id', :to => 'basket#set_count', :as => :set_count
  match '/basket' => 'basket#my_basket', :as => :my_basket

  resources :orders

  resources :shop_sections
  resources :section_categories
  resources :brands

  match '/shop/not_publish' => 'products#not_publish', :as => :shop_not_publish
  match '/shop/archive' => 'products#archive', :as => :shop_archive
  match '/shop/import_catalog' => 'products#import_catalog', :as => :shop_import_catalog
  match '/shop/brands' => 'brands#index', :as => :shop_brands
  match '/shop/:shop_section' => 'products#index', :as => :shop_section_products
  match '/shop/:shop_section/:section_category' => 'products#index', :as => :section_category_products

  match '/product_images/crop/:id' => 'product_images#crop', :as => :crop_product_image
  match '/product_images/update/:id/:cover/:preview/:title' => 'product_images#update'
  match '/product_images/destroy/:id' => 'product_images#destroy'
  match '/product_images/upload' => 'product_images#upload'
  resources :product_images

  match '/post_images/crop/:id' => 'post_images#crop', :as => :crop_post_image
  match '/post_images/update/:id/:cover/:preview/:title' => 'post_images#update'
  match '/post_images/destroy/:id' => 'post_images#destroy'
  match '/post_images/upload' => 'post_images#upload'
  resources :post_images

  match '/magazine' => 'posts#index', :as => :magazine
  match '/magazine/:short_url' => 'posts#show', :as => :magazine_post

  match '/:short_url' => 'statics#show', :as => :show_static
  resources :statics

  resources :welcomes

  root :to => 'welcomes#home'

  match '/access_denied' => 'error#access_denied', :as => :access_denied
  match '/not_found' => 'error#not_found', :as => :not_found
end

app/models/size_to_product.rb
class SizeToProduct < ActiveRecord::Base

  belongs_to :product

  attr_accessible :product_id, :size_id, :product_count

  default_scope order(:size_id)

end

app/controllers/size_to_products_controller.rb
class SizeToProductsController < ApplicationController
  load_and_authorize_resource

  # GET /size_to_products
  # GET /size_to_products.json
  def index
    @size_to_products = SizeToProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @size_to_products }
    end
  end

  # GET /size_to_products/1
  # GET /size_to_products/1.json
  def show
    @size_to_product = SizeToProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @size_to_product }
    end
  end

  # GET /size_to_products/new
  # GET /size_to_products/new.json
  def new
    @size_to_product = SizeToProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @size_to_product }
    end
  end

  # GET /size_to_products/1/edit
  def edit
    @size_to_product = SizeToProduct.find(params[:id])
  end

  # POST /size_to_products
  # POST /size_to_products.json
  def create
    @size_to_product = SizeToProduct.new(params[:size_to_product])

    respond_to do |format|
      if @size_to_product.save
        format.html { redirect_to @size_to_product, notice: 'Size to product was successfully created.' }
        format.json { render json: @size_to_product, status: :created, location: @size_to_product }
      else
        format.html { render action: "new" }
        format.json { render json: @size_to_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /size_to_products/1
  # PUT /size_to_products/1.json
  def update
    @size_to_product = SizeToProduct.find(params[:id])

    respond_to do |format|
      if @size_to_product.update_attributes(params[:size_to_product])
        format.html { redirect_to @size_to_product, notice: 'Size to product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @size_to_product.errors, status: :unprocessable_entity }
      end
    end
  end

  def size_to_product_count
    product_id = params[:product_id]
    size_id = params[:size_id]
    product_count = params[:product_count]
    
    size_to_product = SizeToProduct.find_by_product_id_and_size_id(product_id, size_id)

    unless size_to_product.nil?
      if product_count == 0
        size_to_product.destroy
      else
        size_to_product.product_count = product_count
        size_to_product.save
      end
    else
      size_to_product = SizeToProduct.create(:product_id => product_id, :size_id => size_id, :product_count => product_count)
    end
  end

  # DELETE /size_to_products/1
  # DELETE /size_to_products/1.json
  def destroy
    @size_to_product = SizeToProduct.find(params[:id])
    @size_to_product.destroy

    respond_to do |format|
      format.html { redirect_to size_to_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/size_to_products_helper.rb
module SizeToProductsHelper
end

app/views/size_to_products/_form.html.erb
<%= form_for(@size_to_product) do |f| %>
  <% if @size_to_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@size_to_product.errors.count, "error") %> prohibited this size_to_product from being saved:</h2>

      <ul>
      <% @size_to_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :size_id %><br />
    <%= f.number_field :size_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/size_to_products/edit.html.erb
<h1>Editing size_to_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @size_to_product %> |
<%= link_to 'Back', size_to_products_path %>

app/views/size_to_products/index.html.erb
<h1>Listing size_to_products</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @size_to_products.each do |size_to_product| %>
  <tr>
    <td><%= size_to_product.product_id %></td>
    <td><%= size_to_product.size_id %></td>
    <td><%= link_to 'Show', size_to_product %></td>
    <td><%= link_to 'Edit', edit_size_to_product_path(size_to_product) %></td>
    <td><%= link_to 'Destroy', size_to_product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Size to product', new_size_to_product_path %>

app/views/size_to_products/new.html.erb
<h1>New size_to_product</h1>

<%= render 'form' %>

<%= link_to 'Back', size_to_products_path %>

app/views/size_to_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @size_to_product.product_id %>
</p>

<p>
  <b>Size:</b>
  <%= @size_to_product.size_id %>
</p>


<%= link_to 'Edit', edit_size_to_product_path(@size_to_product) %> |
<%= link_to 'Back', size_to_products_path %>

app/views/size_to_products/size_to_product_count.js.erb
$("<%= "#size_to_product_count-#{params[:product_id]}-#{params[:size_id]}" %>").focus();
$("<%= "#size_to_product_count-#{params[:product_id]}-#{params[:size_id]}" %>").select();