config/routes.rb
Funkyouseven::Application.routes.draw do
  devise_for :users

  post 'markdown/preview'

  match '/size_to_product_count/:product_id/:size_id/:product_count', :to => 'size_to_products#size_to_product_count', :as => :size_to_product_count

  match '/cover_magazines/new_from_post/:post_id', :to => "cover_magazines#new_from_post", :as => :create_cover_magazine_from_post
  resources :cover_magazines

  resources :posts

  match '/products/all/page/:page', :to => "products#all_by_page", :as => :all_products_by_page
  match '/products/section/:section/sex/:sex', :to => "products#sex", :as => :products_by_sex
  match '/products/section/:section/career/:career', :to => "products#career", :as => :products_by_career
  match '/products/section/:section/page/:page', :to => "products#page", :as => :products_by_page
  match '/products/funk_yoo_shot' => "products#funk_yoo_shot", :via => :get
  resources :products

  match '/product_to_look/:product_id/:look_id/:yes', :to => 'product_to_looks#check'

  match '/basket/remove/:product_id/:size_id', :to => 'basket#remove_product', :as => :remove_from_basket
  match '/basket/add/:product_id/:size_id', :to => 'basket#add_product', :as => :add_to_basket
  match '/basket/update_size/:product_count/:product_id/:size_id', :to => 'basket#update_size', :as => :update_size
  match '/basket/empty', :to => 'basket#empty', :as => 'empty_basket', :as => :empty_basket
  match '/basket/:product_count/:product_id/:size_id', :to => 'basket#set_count', :as => :set_count
  match '/basket' => 'basket#my_basket', :as => :my_basket

  resources :orders

  resources :shop_sections
  resources :section_categories
  resources :brands

  match '/shop/not_publish' => 'products#not_publish', :as => :shop_not_publish
  match '/shop/archive' => 'products#archive', :as => :shop_archive
  match '/shop/import_catalog' => 'products#import_catalog', :as => :shop_import_catalog
  match '/shop/brands' => 'brands#index', :as => :shop_brands
  match '/shop/:shop_section' => 'products#index', :as => :shop_section_products
  match '/shop/:shop_section/:section_category' => 'products#index', :as => :section_category_products

  match '/product_images/crop/:id' => 'product_images#crop', :as => :crop_product_image
  match '/product_images/update/:id/:cover/:preview/:title' => 'product_images#update'
  match '/product_images/destroy/:id' => 'product_images#destroy'
  match '/product_images/upload' => 'product_images#upload'
  resources :product_images

  match '/post_images/crop/:id' => 'post_images#crop', :as => :crop_post_image
  match '/post_images/update/:id/:cover/:preview/:title' => 'post_images#update'
  match '/post_images/destroy/:id' => 'post_images#destroy'
  match '/post_images/upload' => 'post_images#upload'
  resources :post_images

  match '/magazine' => 'posts#index', :as => :magazine
  match '/magazine/:short_url' => 'posts#show', :as => :magazine_post

  match '/:short_url' => 'statics#show', :as => :show_static
  resources :statics

  resources :welcomes

  root :to => 'welcomes#home'

  match '/access_denied' => 'error#access_denied', :as => :access_denied
  match '/not_found' => 'error#not_found', :as => :not_found
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  rescue_from NotFound, :with => :not_found
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  def import_catalog
    wear_last_product_number = ShopSection.find_by_short_url("wear").last_product_number
    gear_last_product_number = ShopSection.find_by_short_url("gear").last_product_number
    equipment_last_product_number = ShopSection.find_by_short_url("equipment").last_product_number

    Product.import()

    @wear_imported = ShopSection.find_by_short_url("we.morear").last_product_number - wear_last_product_number
    @gear_imported = ShopSection.find_by_short_url("gear").last_product_number - gear_last_product_number
    @equipment_imported = ShopSection.find_by_short_url("equipment").last_product_number - equipment_last_product_number

    @articles_side_bar = Post.side_bar
    @shop_side_bar = Product.shop_side_bar
  end

  def not_publish
    @products = Product.not_publish

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def archive
    @products = Product.archive

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def funk_yoo_shot
    @products = Product.not_publish

    respond_to do |format|
      format.json { render json: @products }
    end
  end

  def index
    @section = :shop
    condition = ""
    unless params[:shop_section].nil?
      @shop_section = ShopSection.find_by_short_url(params[:shop_section])
      unless @shop_section.nil?
        condition = "products.shop_section_id = #{@shop_section.id}"
        @user_settings["shop_section"] = @shop_section.id
        @user_settings.delete("section_category")
        @user_settings.delete("brand")
      end
    end

    unless @shop_section.nil? && params[:section_category].nil?
      @section_category = SectionCategory.find_by_shop_section_id_and_short_url(@shop_section.id, params[:section_category])
      unless @section_category.nil?
        condition += " and products.section_category_id = #{@section_category.id}"
        @user_settings["section_category"] = @section_category.id
      end
    end

    unless @user_settings["sex"].nil?
      condition += " and products.sex_id = #{@user_settings['sex']}"
    end

    unless @user_settings["career"].nil?
      unless @shop_section.nil?
        condition += " and products.career_id = #{@user_settings['career']}" if @shop_section.short_url != "wear"
      else
        condition += " and products.career_id = #{@user_settings['career']}"
      end
    end

    @page = (params[:page] || 1).to_i

    @products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    @more_products = nil if @more_products <= 0

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def all_by_page
    condition = "0 = 0"

    unless @user_settings["sex"].nil?
      condition += " and products.sex_id = #{@user_settings["sex"]}"
    end

    unless @user_settings["career"].nil?
      condition += " and products.career_id = #{@user_settings["career"]}"
    end

    @page = (params[:page] || 1).to_i

    @products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    #@more_products = nil if @more_products <= 0

    render :layout => false
  end

  def page
    @section = params[:section]

    condition = "0 = 0"

    unless @user_settings["shop_section"].nil? || @user_settings["brand"]
      @shop_section = ShopSection.find(@user_settings["shop_section"])
      condition += " and products.shop_section_id = #{@shop_section.id}"
    end

    if !@shop_section.nil? && !@user_settings["section_category"].nil?
      @section_category = SectionCategory.find(@user_settings["section_category"])
      unless @section_category.nil?
        condition += " and products.section_category_id = #{@section_category.id}"
      end
    end

    unless @user_settings["sex"].nil?
      condition += " and products.sex_id = #{@user_settings["sex"]}"
    end

    unless @user_settings["career"].nil?
      unless @shop_section.nil?
        condition += " and products.career_id = #{@user_settings["career"]}" unless @shop_section.short_url == "wear"
      else
        condition += " and products.career_id = #{@user_settings["career"]}"
      end
    end

    unless @user_settings["brand"].nil?
      condition += " and products.brand_id = #{@user_settings["brand"]}" if @section == 'brands'
    end

    @page = (params[:page] || 1).to_i

    @products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    @more_products = nil if @more_products <= 0

    render :layout => false
  end

  def sex
    @section = params[:section]

    condition = "0 = 0"

    unless @user_settings["shop_section"].nil?
      @shop_section = ShopSection.find(@user_settings["shop_section"])
      condition += " and products.shop_section_id = #{@shop_section.id}"
    end

    if !@shop_section.nil? && !@user_settings["section_category"].nil?
      @section_category = SectionCategory.find(@user_settings["section_category"])
      unless @section_category.nil?
        condition += " and products.section_category_id = #{@section_category.id}"
      end
    end

    unless @user_settings["career"].nil?
      unless @shop_section.nil?
        condition += " and products.career_id = #{@user_settings["career"]}" unless @shop_section.short_url == "wear"
      else
        condition += " and products.career_id = #{@user_settings["career"]}"
      end
    end

    unless @user_settings["brand"].nil?
      condition += " and products.brand_id = #{@user_settings["brand"]}" if @section == "brands"
    end

    unless params[:sex].nil?
      if params[:sex] == "empty"
        @user_settings.delete("sex")
      else
        condition += " and products.sex_id = #{params[:sex]}"
        @user_settings["sex"] = params[:sex]
      end
    end

    @page = 1

    @products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    @more_products = nil if @more_products <= 0

    render :layout => false, :action => "selectors"
  end

  def career
    @section = params[:section]

    condition = "0 = 0"

    unless @user_settings["shop_section"].nil?
      @shop_section = ShopSection.find(@user_settings["shop_section"])
      condition += " and products.shop_section_id = #{@shop_section.id}"
    end

    if !@shop_section.nil? && !@user_settings["section_category"].nil?
      @section_category = SectionCategory.find(@user_settings["section_category"])
      unless @section_category.nil?
        condition += " and products.section_category_id = #{@section_category.id}"
      end
    end

    unless @user_settings["sex"].nil?
      condition += " and products.sex_id = #{@user_settings["sex"]}"
    end

    unless @user_settings["brand"].nil?
      condition += " and products.brand_id = #{@user_settings["brand"]}" if @section == "brands"
    end

    unless params[:career].nil?
      if params[:career] == "empty"
        @user_settings.delete("career")
      else
        condition += " and products.career_id = #{params[:career]}"
        @user_settings["career"] = params[:career]
      end
    end

    @page = 1

    @products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    @more_products = nil if @more_products <= 0

    render :layout => false, :action => "selectors"
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    @basket.add_last_item(@product)

    @shop_section = @product.shop_section
    @section_category = @product.section_category

    @more_looks = Product.more_looks(@product.id)

    @page = (params[:page] || 1).to_i
    condition = "0 = 0"

    unless @shop_section.nil?
      condition += " and products.shop_section_id = #{@shop_section.id}"
      condition += " and products.section_category_id = #{@section_category.id}" unless @section_category.nil?
      condition += " and products.sex_id = #{@user_settings["sex"]}" unless @user_settings["sex"].nil?
      condition += " and products.career_id = #{@user_settings["career"]}" unless @shop_section.short_url == "wear" || @user_settings["career"].nil?
    end

    @related_products = Product.where(condition).valid_products.order("products.updated_at DESC").paginate(:page => @page)
    @more_products = Product.where(condition).valid_products.all.size() - Product.per_page * @page
    @more_products = nil if @more_products <= 0

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

# GET /products/new
# GET /products/new.json
  def new
    @product = Product.new
    @looks = Product.all_looks

    respond_to do |format|
      format.html { render layout: "editor" }
      format.json { render json: @product }
    end
  end

# GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @looks = Product.all_looks

    render layout: "editor"
  end

# POST /products
# POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        @looks = @product.looks

app/helpers/products_helper.rb
#encoding: utf-8
module ProductsHelper

  def format_price(price)
    number_to_currency(price, :precision => 0, :unit => "p.")
  end

  def product_title_position(product)
    "style=left:#{product.title_x}px;top:#{product.title_y}px";
  end

  def product_title(product, container = false)
    unless container
      title = product.title.gsub("{", "")
      title = title.gsub("}", "")
    else
      title = product.title.gsub("{", "<#{container} style='color: #{product.title_color} !important;'>")
      title = title.gsub("}", "</#{container}>")
    end
    title
  end

  def product_sizes(product)
    wear = ProductSize.collection("wear")
    shoes = ProductSize.collection("shoes")
    order = ProductSize.collection("order")

    output = ""

    output += "<label><b>Одежда</b></label><div class='clear'></div>"

    wear.each do |size|
      output += "<div class='size_unit'><label>#{size.name}</label>" + text_field_tag("size_to_product_count-#{product.get_id}-#{size.code}", product.count_by_size_id(size.code), :onkeyup => "onKeyUpSizeCount(event, #{product.get_id}, #{size.code});") + "</div>"
    end

    output += "<div class='clear'></div><label><b>Обувь</b></label><div class='clear'></div>"
    shoes.each do |size|
      output += "<div class='size_unit'><label>#{size.name}</label>" + text_field_tag("size_to_product_count-#{product.get_id}-#{size.code}", product.count_by_size_id(size.code), :onkeyup => "onKeyUpSizeCount(event, #{product.get_id}, #{size.code});") + "</div>"
    end
    raw output
  end
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true}) do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field product-cover-preview">
      <%= image_tag @product.get_cover.image.url(:slider) %>

      <%= f.hidden_field :title_x %>
      <%= f.hidden_field :title_y %>

      <div <%= product_title_position(@product) %> id="product_cover_title" class="draggable">
        <%= link_to raw(product_title(@product, "span") + "<p>" + format_price(@product.price) + "</p>"), "#" unless @product.new_record? %>
      </div>
    </div>

    <div class="clear-8"></div>

    <div class="field">
      <label><span>*</span><%= t("activerecord.attributes.product.title") %></label>
      <%= f.text_area :title, :class => "title", :onkeyup => "update_title_preview()" %>
    </div>

    <div class="field product_selects">
      <%= f.label :title_color %>
      <%= f.collection_select(:title_color, MyColor.collection, :code, :name, {}, {:onchange => "update_title_preview()"}) %>

      <%= f.label :use_background %>
      <%= f.check_box :use_background %>

      <%= f.label :sex_id %>
      <%= f.collection_select(:sex_id, Sex.collection, :code, :name, {:include_blank => "не установлен"}) %>

      <div class="clear-8"></div>

      <%= f.label :brand_id %>
      <%= f.collection_select(:brand_id, Brand.all, :id, :name, {:include_blank => "не установлен"}) %>


      <%= f.label :career_id %>
      <%= f.collection_select(:career_id, Career.collection, :code, :name, {:include_blank => "не установлен"}) %>

      <div class="clear-8"></div>
      <%= f.label :shop_section_id %>
      <%= f.collection_select(:shop_section_id, ShopSection.all, :id, :name, {:include_blank => "не установлен"}) %>


      <%= f.label :section_category_id %>
      <%= f.collection_select(:section_category_id, SectionCategory.all, :id, :name, {:include_blank => "не установлен"}) %>

      <div class="clear-8"></div>
      <%= f.label :look %>
      <%= f.check_box :look, :onchange => "updateProductLook(#{@product.id});" %>

      <%= f.label :archive %>
      <%= f.check_box :archive %>

      <%= f.label :welcome_position_id %>
      <%= f.collection_select(:welcome_position_id, WelcomePosition.collection, :code, :name, {:include_blank => "не установлен"}) %>

    </div>

    <div class="field">
      <label><span>*</span><%= t("activerecord.attributes.product.description") %></label>
      <%= f.text_area :description, :class => "product_description" %>
    </div>

    <div class="field for_look <%= "hidden" unless @product.look %>">
      <label><span>*</span><%= t("activerecord.attributes.product.discount") %></label>
      <%= f.text_field :discount, :class => "title" %>
    </div>

    <div class="field">
      <label><span>*</span><%= t("activerecord.attributes.product.price") %></label>
      <%= f.text_field :price, :class => "price", :onkeyup => "update_title_preview()" %>
    </div>

    <div class="field">
      <%= f.label :color %>
      <br/>
      <%= f.text_field :color %>
    </div>

    <div class="field product_sizes not_for_look <%= "hidden" if @product.look %>">
      <%= label :look, t("activerecord.attributes.product.products_into_look") %>
      <div class="clear-8"></div>
      <% @looks.each do |look| %>
          <div class="looks">
            <%= image_tag look.get_cover.image.url(:preview_circle) %>
            <%= check_box :look, :product, :id => "#{@product.id}-#{look.id}", :checked => @product.into_look(look), :onchange => "processProductToLook(#{@product.id}, #{look.id})" %>
            <%= raw product_title(look) %>
          </div>
      <% end unless @looks.nil? %>
    </div>

    <div class="field product_sizes for_look <%= "hidden" unless @product.look %>">
      <%= label :look, t("activerecord.attributes.product.products_to_look") %>
      <div class="clear-8"></div>
      <% @product.products.each do |product| %>
          <div class="looks">
            <%= image_tag product.get_cover.image.url(:preview_circle) %>
            <%= image_tag product.get_preview.image.url(:preview_circle) %>
            <br/>
            <%= check_box :product, :look, :id => "#{product.id}-#{@product.id}", :checked => @product.has_product(product), :onchange => "processProductToLook(#{product.id}, #{@product.id})" %>
            <%= raw product_title(product, "span") %>
          </div>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :composition %>
      <br/>
      <%= f.text_field :composition %>
    </div>

    <div class="field">
      <%= f.label :season %>
      <br/>
      <%= f.text_field :season %>
    </div>

    <div class="field product_sizes">
      <%= f.label :size %>
      <div class="clear"></div>
      <%= product_sizes(@product) %>
      <div class="clear"></div>
    </div>

    <div class="field">
      <%= render :partial => 'product_images/files_upload', :locals => {:product => @product} %>
    </div>

    <div class="clear"></div>

    <%= f.hidden_field :preview_id %>

    <div class="actions">
      <br/>
      <%= f.submit %>
    </div>
<% end %>

app/views/products/_list.html.erb
<%= link_to 'New Product', new_product_path %>

<% @products.each do |product| %>
    <%= product.title %>
    <%= product.price %>
    <%= product.description %>
    <%= product.color %>
    <%= product.composition %>
    <%= product.brand_id %>
    <%= product.sex_id %>
    <%= product.career_id %>
    <%= product.shop_section_id %>
    <%= product.category_id %>
    <%= product.look_id %>
    <%= product.season %>
    <%= product.welcome_position_id %>
    <%= link_to 'Edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %>
<% end %>

app/views/products/_product_basket_item.html.erb
<div id="<%= "#{basket_item.product.id}-#{basket_item.product_size}" %>" class="cat <%= "new" if margin_top %> <%= "cat_item" unless cat_item.nil? %> <%= container_class unless container_class.nil? %>">
  <%= link_to image_tag(basket_item.preview_url, :alt => basket_item.title, :width => 300), basket_item.product, :class => "link_img" %>
  <% if basket_item.initial_size == 55 %>
      <%= link_to raw(product_title(basket_item.product)), basket_item.product, :class => "title", :title => product_title(basket_item.product) %>
      <span class="stuff-price"><%= format_price(basket_item.product.price.round) %></span>

      <form>
        <label>Количество</label>
        <%= text_field_tag "counter-#{basket_item.product.id}-#{basket_item.product_size}", basket_item.product_count, :onkeyup => "onKeyUp(event, #{basket_item.product.id}, #{basket_item.product_size});" %>
        <%= link_to t("backend.actions.destroy"), remove_from_basket_path(basket_item.product.id, basket_item.product_size), :remote => true, :class => "delete" %>
      </form>
      <%= collection_select(:size, "#{basket_item.product.id}-#{basket_item.product_size}", basket_item.all_sizes, :code, :name, {:selected => basket_item.product_size}, {:onchange => "setMySize(#{basket_item.product.id}, #{basket_item.product_size})"}) %>
  <% else %>
      <%= link_to raw(product_title(basket_item.product) + " (" + ProductSize.by_code(basket_item.product_size) + (basket_item.initial_size != basket_item.product_size ? " / #{ProductSize.by_code(basket_item.initial_size)}" : "") + ")"), basket_item.product, :class => "title", :title => product_title(basket_item.product) %>
      <span class="stuff-price"><%= format_price(basket_item.product.price.round) %></span>

      <form>
        <label>Количество</label>
        <%= text_field_tag "counter-#{basket_item.product.id}-#{basket_item.product_size}", basket_item.product_count, :onkeyup => "onKeyUp(event, #{basket_item.product.id}, #{basket_item.product_size});" %>
        <%= link_to t("backend.actions.destroy"), remove_from_basket_path(basket_item.product.id, basket_item.product_size), :remote => true, :class => "delete" %>
      </form>
  <% end %>
</div>

app/views/products/_product_big_preview_item.html.erb
<div class="list_preview">
  <div class="list_big_preview">
    <%= image_tag product.get_cover.image.url(:slider) %>
    <div <%= product_title_position(product) %> class="big_preview_title">
      <%= link_to raw(product_title(product, 'span') + content_tag(:p, format_price(product.price))), product, :class => "title" %>
    </div>
  </div>
</div>

app/views/products/_product_preview_item.html.erb
<div class="list_preview list_small_preview">
  <%= link_to image_tag(product.get_preview.image.url([:preview_item_higher, :preview_item][rand(2)]), :alt => product.title), product, :class => "link_img" %>
  <%= link_to raw(product_title(product)), product, :class => "title" %>
  <br/>
  <span><%= number_to_currency(product.price.round, :precision => 0, :unit => "p.") unless product.price.nil? %></span>
</div>

app/views/products/_product_small_preview_item.html.erb
<div class="preview_small">
  <div class="preview_circle" style="background: url('<%= product.get_cover().image.url(:preview_circle) %>') no-repeat scroll 0 0 transparent;">
  </div>
  <%= link_to raw(product_title(product, "span")), product %>
  <span><%= number_to_currency(product.price.round, :precision => 0, :unit => "p.") unless product.price.nil? %></span>
</div>

app/views/products/archive.html.erb
<% @products.each_with_index do |product, i| %>
    <%= render "products/product_preview_item", :product => product, :cat_item => true, :margin_top => false, :container_class => (i+1)%3 == 0 ? "no_margin" : "" %>
<% end %>

<div class="clear"></div>
<!--<a class="more" href="#">Показать еще 25 из 100</a>-->

app/views/products/edit.html.erb
<div class="center_item">

  <div class="main noborder">
    <h1><%= t('backend.titles.editing', :model => t('activerecord.model.product')) %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div id="full_list">
  <%= render "products/page", :target => @products %>

  <nav id="page-nav">
    <%= link_to "next page", products_by_page_path(@section, @page + 1), :remote => true unless @more_products.nil? %>
  </nav>
</div>

app/views/products/not_publish.html.erb
<% @products.each_with_index do |product, i| %>
    <%= render "products/product_preview_item", :product => product, :cat_item => true, :margin_top => false, :container_class => (i+1)%3 == 0 ? "no_margin" : "" %>
<% end %>

<div class="clear"></div>
<!--<a class="more" href="#">Показать еще 25 из 100</a>-->

app/views/products/page.js.erb
$(".more").replaceWith("<%= escape_javascript(render("products/page", :target => @products)) %>");

app/views/products/selectors.js.erb
if ($('#brand_products').length > 0) {
    $('#brand_products').html("<%= escape_javascript(render "products/page", :target => @products) %>");
} else {
    $('#content').html("<%= escape_javascript(render "products/page", :target => @products) %>");
}

app/views/products/show.html.erb
<%= meta_tags (@product) %>

<div class="main_item">
  <div class="description <%= 'use-backround' if @product.use_background? %>">
    <form>
      <h1><%= raw product_title(@product, "span") %></h1>
      <%= raw "<h2>" + number_to_currency(@product.price.round, :precision => 0, :unit => "p.") + (@product.look && !@product.discount.nil? ? "(-" + @product.discount.to_s + "%)" : "") + "</h2>" unless @product.price.nil? %>
      <%= raw "<p>#{@product.description}</p>" unless @product.description.nil? || @product.description.empty? %>
      <%= raw "<p><span>Производитель:</span> #{@product.brand.name}</p>" unless @product.brand.nil? %>
      <%= raw "<p><span>Пол:</span> #{Sex.by_code(@product.sex_id)}</p>" unless @product.sex_id.nil? %>
      <%= raw "<p><span>Цвет:</span> #{@product.color}</p>" unless @product.color.nil? || @product.color.empty? %>
      <%= raw "<p><span>Состав:</span> #{@product.composition}</p>" unless @product.composition.nil? || @product.composition.empty? %>
      <%= raw "<p><span>Сезон:</span> #{@product.season}</p>" unless @product.season.nil? || @product.season.empty? %>
      <%#= raw "<p><span>В составе сета:</span> " + link_to( product_title(@product.looks.first), @product.looks.first) + "</p>" unless @product.looks.empty? || @product.look %>
      <%= collection_select(:product_size, :id, @product.available_sizes, :code, :name, {:include_blank => "Размер"}, {:onchange => "setSize()"}) %>
      <div class="clear"></div>
      <span id="add_product_button" class="add" href="#" onclick="checkHref()" link="<%= add_to_basket_path(@product.id, "") %>"><%= t("activerecord.attributes.basket.to_basket") %></span>
      <%#= t("activerecord.attributes.basket.to_basket"), "#", :id => "add_product_button", :link => add_to_basket_path(@product.id, ""), :class => "add",  %>
      <div class="clear"></div>
      <%= link_to "Все вещи #{@product.brand.name}", @product.brand, :class => "all_w" unless @product.brand.nil? %>
      <%= link_to " ", @product.looks.first, :class => "all_w" unless @product.looks.empty? %>
    </form>
  </div>

  <%= image_tag @product.get_cover.image.url(:full), :alt => @product.title, :id => :current_image, :class => :current_image %>
  <ul class="product_previews">
    <% @product.product_images.each_with_index do |image, i| %>
        <% if i < 6 %>
            <li>
              <div image_url="<%= image.image.url(:full) %>" style="background: url('<%= image.image.url(:preview_circle) %>') no-repeat scroll 0 0 transparent;"></div>
            </li>
        <% end %>
    <% end %>
  </ul>
</div>
<div class="clear"></div>

<% if @product.look %>
    <div class="relaited">Товары в сете</div>
    <div class="clear"></div>

    <%= render "products/page", :target => @product.products %>
    <% if @product.products.empty? %>
        <p><%= t("activerecord.attributes.product.products_empty") %></p>
    <% end %>
    <div class="clear"></div>

    <div class="relaited">Еще сеты</div>
    <div class="clear"></div>

    <%= render "products/page", :target => @more_looks %>
    <div class="clear"></div>
<% else %>
    <div class="relaited">Товары в этой категории</div>
<% end %>

<div id="full_list">
  <%= render "products/page", :target => @related_products %>
  <!--<nav id="page-nav">-->
    <!--<%#= link_to "", products_by_page_path(@product.shop_section.short_url, @page + 1), :remote => true unless @more_products.nil? %>-->
  <!--</nav>-->
</div>